### ISSUE TITLE
Long output names doesn't wrap in side menu

### ISSUE THREAD

**Issue by kstep** [notandy/ympd#112]
![2015-12-14-151237_271x104_scrot](https://cloud.githubusercontent.com/assets/28537/11780745/54f70a32-a275-11e5-8362-08c5d6ecc568.png)

**Comment by LordMyschkin** [comment]
was already closed (issue #99) but did somehow reappear...

**Comment by LordMyschkin** [comment]
very easy fix - just include following lines in the mpd.css
button {
  overflow: hidden;
}
and run a make

**Comment by notandy** [comment]
fixed with latest commit
