### ISSUE TITLE
Dirble stuck to Loading web radios

### ISSUE THREAD

**Issue by archphile** [notandy/ympd#115]
Hi all,

I recently made a new build of ympd. I decided to try dirble but it sticks on Loading web radios.

Is there any way of make it functional?

Many thanks,

Michael

**Comment by Nofre** [comment]
Sorry, I deleted my api key from Dirble and now the code doesn't work. You can generate your own key at dirble.com and replace the 6 ocurrences of "token=2e223c9909593b94fc6577361a" in mpd.js.

I want to do a patch to solve it, but I have no time.
