### ISSUE TITLE
Jukebox Mode

### ISSUE THREAD

**Issue by jjg** [notandy/ympd#133]
There may already be a way to do this, but I wasn't able to find it.

Old-fashioned jukeboxes worked by playing songs that people selected, but when this list was exhausted, the jukebox would play "random" music until more songs were deliberately selected.

It would be cool if ympd had a mode like this, where it would play the contents of the queue, playing each song once (like "consume") and then switching to global shuffle mode when the queue was empty.  If additional tracks are added to the queue, it switches back to playing queued songs until they are once again exhausted.

This would be a great for group environments where people could use their phones to add songs to the queue, but also make sure something is always playing (also random music tends to encourage people to pick songs they like :)

**Comment by steveww** [comment]
This could be done by creating a big queue and enabling random. A little tweak to add track to put it second in the queue; after the currently playing song.

**Comment by BenjaminHae** [comment]
I think that's something that should be implemented in mpd and not in a client.

**Comment by jjg** [comment]
I hadn't considered that @BenjaminHae, I'll pursue that route first.
