### ISSUE TITLE
Dirble tab stuck at "Loading..." with new API key

### ISSUE THREAD

**Issue by af7567** [notandy/ympd#138]
When clicking on the Dirble tab it gets stuck at loading the categories.
I saw the old issue about the API key changing, so I created an API key and updated my mpd.js and recompiled.  If I view the page source I can see that the correct API key is being used and if I visit the URL used to get the categories then I see the JSON data.  

I guess the data returned from Dirble has changed and ympd can't parse it anymore?

**Comment by tatoosh** [comment]
Linked to #140 
Debugging shows that the http server needs to allow cross domain.
How to do so?
