### ISSUE TITLE
Usage behind Apache Proxy

### ISSUE THREAD

**Issue by ne0h** [notandy/ympd#24]
Hey,

i want to use ympd behind an apache2 proxy to have a shorter and more comfortable domain.
This is the vhost i have defined:

<VirtualHost *:80>

```
    ServerName music

    ProxyRequests Off
    <Proxy *>
            Order deny,allow
            Allow from all
    </Proxy>
    ProxyPass               /       http://mediacenter:9080/
    ProxyPassReverse        /       http://mediacenter:9080/
```

</VirtualHost>

When i navigate there by browser, it error is "Connection to ympd lost, retrying in 3 seconds". Firefox goes a little bit more into details and complains about "Firefox kann keine Verbindung zu dem Server unter ws://music/ aufbauen. mpd.js:121
"disconnected"

Is there someting i can do?

Thanks!

**Comment by sedrubal** [comment]
I'm also interested in an apache config... This doesn't work:

```apache
    <IfModule mod_proxy.c>
        <IfModule mod_proxy_http.c>
            ProxyVia On
            ProxyRequests Off
            ProxyPass / http://localhost:8080/
            ProxyPassReverse / http://localhost:8080/
            ProxyPass "/ws/"  "ws://localhost:8080/ws/"
            ProxyPreserveHost Off
            <Proxy *>
                Options FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
                Require all granted
            </Proxy>
            <Location />
                Order allow,deny
                Allow from all
                Require all granted
            </Location>
        </IfModule>
    </IfModule>
```

**Comment by krzole** [comment]
Hi,

Below that does work with ympd (and possibly other applications based on WebSockets):
k-rpi is a music server with mpd + ympd, hidden behind NAT
```
<VirtualHost *:8080>
        ServerName k-rpi.hostname
        ProxyRequests Off
        ProxyPass          / ws://k-rpi/
</VirtualHost>

<Proxy http://k-rpi/*>
        Order deny,allow
        Allow from all
</Proxy>
```

**Comment by ryanczak** [comment]
This also works:

<Location /ympd>
RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /ympd/(.*)           ws://localhost:8082/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /ympd/(.*)           http://localhost:8082/$1 [P,L]
ProxyPassReverse http://localhost:8082
</Location>
