### ISSUE TITLE
CLI options issue

### ISSUE THREAD

**Issue by mxjeff** [notandy/ympd#53]
I'm noticing a strange behaviour with CLI options:

```bash
$ ympd  
MPD Connecting to 127.0.0.1:6600
MPD connected.
```

But then if I use an explicit port number I got:
```
$ ympd  -p6600
Mongoose error: Cannot bind to port
```

What did I get wrong?

**Comment by GrayShade** [comment]
It's an older bug, fixed here: https://github.com/notandy/ympd/commit/9728aae69c95592ab54c69a88186324907a8d0ff

**Comment by mxjeff** [comment]
Alright thanks GrayShade, I forgot to mention I'm running latest release v1.2.3.
