### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by maheshmarkus** [notandy/ympd#59]
I am running ympd as a service. 

It would be good if there was a configuration file, so I could specify the webport (i.e. change it to 80 from 8080).

I expect this to be a documentation issue :)

Cheers,
Mahesh

**Comment by maheshmarkus** [comment]
I solved my problem by editing /etc/init.d/ympd

I changed DAEMON_OPT="--user $YMPD_USER --webport 80"

I think updating the documentation to help install ympd as a service would be useful.

Thanks,
Mahesh

**Comment by notandy** [comment]
How daemon options are applied is distribution specific, but I consider add it to the documentation.
