### ISSUE TITLE
Trying to set up nginx reverse proxy

### ISSUE THREAD

**Issue by m45t3r** [notandy/ympd#77]
Hi

I am trying to set up a ``nginx`` reverse proxy for ``ympd`` to use ``https`` and allow basic authentication of the service. I did the following:

    # https only
    server {
        listen       443 ssl;
        server_name  127.0.0.1;
        root /srv/http;
        index index.html index.php index.htm;

        ssl_certificate      cert.crt;
        ssl_certificate_key  cert.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m; 

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on; 

        # Without the ^~ the static files like css and js would not load.
        location ^~ /ympd {
             # Basic HTTP auth
             auth_basic "Welcome to ympd on mikupi!";
             auth_basic_user_file /etc/nginx/.htpasswd;
             # Reverse proxy
             proxy_pass http://127.0.0.1:8080;
             # Websocket
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade"; 
             # Without this I would get "Not found"
             rewrite /ympd/(.*) /$1 break;
             proxy_redirect off;
        }
    }

Trying to debug using Firefox, it seems that the Websocket requests are being denied by the webserver. This is the kind of error that get logged in my ``/var/log/nginx/error.log``:

    2015/06/08 23:45:46 [error] 10080#0: *270 directory index of "/srv/http/" is forbidden, client: 192.168.1.11, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "192.168.1.15"
    2015/06/08 23:46:46 [error] 10080#0: *316 directory index of "/srv/http/" is forbidden, client: 192.168.1.11, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "192.168.1.15"
    2015/06/08 23:47:46 [error] 10080#0: *360 directory index of "/srv/http/" is forbidden, client: 192.168.1.11, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "192.168.1.15"
    2015/06/08 23:48:46 [error] 10080#0: *405 directory index of "/srv/http/" is forbidden, client: 192.168.1.11, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "192.168.1.15"
    2015/06/08 23:49:47 [error] 10080#0: *452 directory index of "/srv/http/" is forbidden, client: 192.168.1.11, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "192.168.1.15"

Or my ``/var/log/nginx/access.log``:

    192.168.1.11 - - [08/Jun/2015:23:57:47 -0300] "GET / HTTP/1.1" 403 141 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"

Seeing issue #24 it seems reverse proxy with nginx should work, but what am I doing wrong?

**Comment by laclaro** [comment]
Has anyone succeeded here? The problem seems to be the redirecting of the "websocket".

**Comment by Amarandus** [comment]
Yes, it works for me. Here is the essential part of my configuration. I stripped away other locations, so it MIGHT be broken for itself, but the essential part is the block "location /ympd/" (the trailing / is important):

```
    server {
        listen       443 ssl;
        ssl_certificate      cert.crt;
        ssl_certificate_key  cert.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        location /ympd/ {
                proxy_pass http://127.0.0.1:9437/;
                proxy_redirect off;
        }
    } 

```

**Comment by m45t3r** [comment]
My current config:

        # Added an trailing / here
        location /ympd/ {
             auth_basic "Welcome to ympd on mikupi!";
             auth_basic_user_file /etc/nginx/.htpasswd;
             # And here too
             proxy_pass http://127.0.0.1:8080/;

             #proxy_set_header X-Real-IP $remote_addr;
             #proxy_set_header Host $host;
             #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";

             #rewrite /ympd/(.*) /$1 break;
             proxy_redirect off;
        }

Still not working, this is the result
![ympd](https://cloud.githubusercontent.com/assets/844343/10409459/8234b6a4-6ef7-11e5-89f3-6d0e24fc55d8.jpg)

The JS and CSS files didn't load, and of course the whole thing is not working.

**Comment by m45t3r** [comment]
Decided to update ympd to lastest git (I was using the stable v1.2.3 before), and using the configuration I posted in OP, it is finally working (the configuration posted by @Amarandus did not work for me btw).

I will close this issue.

**Comment by laclaro** [comment]
I got it working


```
upstream ympd {
  server    localhost:8081;
  keepalive 512;
}

# redirect port 80 to 443 HTTPS
server {
    listen 80 default_server;
    server_name _;
    if ($uri_preferred_protocol = "https") {
      return 301 https://$host$request_uri;
    }

}

# SSL Server
server {
        listen 443 ssl default_server;
        server_name ympd_proxy;

        # enable ssl
        ssl on;
        ssl_certificate /etc/ssl/certs/self-signed-cert.crt;
        ssl_certificate_key /etc/ssl/private/self-signed-cert.key;

        # webroot directory
        root /var/www/html;
        # index files
        index index.html;

        location / {try_files $uri $uri/ =404;}

        # ympd proxy settings for /ympd
        location /ympd {
            rewrite            ^/ympd(.*)  /$1  break;
            proxy_redirect     http://ympd   /ympd/;
            proxy_set_header   Host $http_host;
            proxy_redirect     off;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Scheme $scheme;
            proxy_pass         http://ympd$uri;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }

        location ~ ^/(css|assets|fonts|js) {
            proxy_pass         http://ympd;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }
}
```

**Comment by moretocome** [comment]
Thanks @laclaro this config works for me as well :)
