### ISSUE TITLE
White spaces are replaced by %20 and as a result files are not found

### ISSUE THREAD

**Issue by therealmuffin** [notandy/ympd#80]
Hello,

I've run ympd as a test a couple of months ago and it worked excellent. However, now I reinstalled/configured my system and I can't add music to the playlist anymore in ympd. Spaces are replaced by '%20' and as a result MPD can't find the file it's supposed to add to the playlist. Other clients work fine. In the log of MPD I find the following:
db: No such song: Flac/Billie%20Holiday%20-%20The%20Complete%20Masters%20%5BDisc%206%EF%BC%9A%201939-1940%5D/02%20Billie%20Holiday%20-%20Long%20Gone%20Blues.flac

In both the test as final setup I ran Voyage Linux 0.10, based on Debian Jessie. Configuration in both cases is nearly identical though packages installed through apt could have been upgraded in the meantime.

Any ideas how to fix this?

Kind regards, Maarten

**Comment by hsoft** [comment]
This might be related to my own PR, #78, merged lately. I didn't have the same problem though...

**Comment by hsoft** [comment]
Oh, sorry, I *do* have the same problem! It's my fault then, my PR was incomplete, sorry about that. I'm checking that out.

**Comment by therealmuffin** [comment]
Thanks, that seems to fix the issue effectively!!
