### ISSUE TITLE
Long outputnames do destroy interfaces beauty

### ISSUE THREAD

**Issue by LordMyschkin** [notandy/ympd#99]
Just see attached screenshot.
![screenshot 2015-09-27 22 33 34](https://cloud.githubusercontent.com/assets/11705882/10125071/f3eba08a-6567-11e5-9692-bec9ec78d863.png)

**Comment by BenjaminHae** [comment]
I propose moving the device buttons to settings.

**Comment by SuperBFG7** [comment]
I consider them to be mute/unmute buttons for different outputs and would therefore keep them where they are. 

But I also don't think this is a real problem: just give it a shorter name. :)

**Comment by LordMyschkin** [comment]
I agree - a very minor concern. Am I suposed to close it at this point?

**Comment by BenjaminHae** [comment]
Maybe all the buttons should crop text when it's too long:
http://stackoverflow.com/questions/3695435/crop-text-too-long-inside-div

**Comment by SuperBFG7** [comment]
Excellent idea!

**Comment by LordMyschkin** [comment]
fixed perfectly
